#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Generate/overwrite the teaching notebooks under ./notebooks/.

This repo stores notebooks as plain JSON. Editing them by hand is painful; this
script provides a consistent way to regenerate them.

Notes:
- Python 3.8 compatible.
- Standard library only.
- Writes UTF-8 JSON (no BOM).
"""

from __future__ import annotations

import json
import textwrap
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional


NBFORMAT = 4
NBFORMAT_MINOR = 5


def _cell_id() -> str:
    return uuid.uuid4().hex[:8]


def _lines(text: str) -> List[str]:
    text = textwrap.dedent(text).lstrip("\n")
    if not text:
        return []
    if not text.endswith("\n"):
        text += "\n"
    return [line + "\n" for line in text.splitlines()]


def md(text: str) -> dict:
    return {"cell_type": "markdown", "id": _cell_id(), "metadata": {}, "source": _lines(text)}


def code(src: str) -> dict:
    return {
        "cell_type": "code",
        "id": _cell_id(),
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _lines(src),
    }


def nb(cells: List[dict]) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.8"},
        },
        "nbformat": NBFORMAT,
        "nbformat_minor": NBFORMAT_MINOR,
    }


def write_nb(path: Path, notebook: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(notebook, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


@dataclass(frozen=True)
class Point:
    title: str
    detail_md: str
    demo: Optional[str] = None


@dataclass(frozen=True)
class Topic:
    no: str
    filename: str
    title_zh: str
    title_en: str
    overview: str
    prerequisites: List[str]
    checklist: List[str]
    points: List[Point]
    mini_case_title: str
    mini_case_md: str
    mini_case_code: str
    self_check: List[str]
    exercises: List[str]


COMMON_NOTE = "> 约定：Python 3.8；示例尽量只用标准库；代码块可直接运行。"

ARTIFACTS_SETUP = """\
from pathlib import Path

ART = Path('_nb_artifacts')
ART.mkdir(exist_ok=True)
print('artifacts dir:', ART.resolve())
"""


TOPICS: List[Topic] = []


def build(topic: Topic) -> dict:
    prereq = "\n".join([f"- {x}" for x in (topic.prerequisites or [])]) or "- 无"
    checklist = "\n".join([f"- [ ] {x}" for x in (topic.checklist or [])]) or "- [ ] 无"
    toc = "\n".join([f"- {i+1}. {p.title}" for i, p in enumerate(topic.points)])

    cells: List[dict] = [
        md(
            f"""\
            # {topic.no}. {topic.title_zh}（{topic.title_en}）

            {topic.overview.strip()}

            {COMMON_NOTE}
            """
        ),
        md(f"## 前置知识\n\n{prereq}\n"),
        md(f"## 知识点地图\n\n{toc}\n"),
        md(f"## 自检清单（学完打勾）\n\n{checklist}\n"),
    ]

    for i, p in enumerate(topic.points, start=1):
        cells.append(md(f"## 知识点 {i}：{p.title}\n\n{p.detail_md.strip()}\n"))
        if p.demo:
            cells.append(code(p.demo))

    cells.append(md(f"## 综合小案例：{topic.mini_case_title}\n\n{topic.mini_case_md.strip()}\n"))
    if topic.mini_case_code.strip():
        cells.append(code(topic.mini_case_code))

    cells.append(md("## 自测题（不写代码也能回答）\n\n" + "\n".join([f"- {q}" for q in topic.self_check]) + "\n"))
    cells.append(md("## 练习题（建议写代码）\n\n" + "\n".join([f"- {q}" for q in topic.exercises]) + "\n"))

    return nb(cells)


def generate() -> None:
    out_dir = Path("notebooks")
    out_dir.mkdir(exist_ok=True)

    if not TOPICS:
        print(
            "TOPICS is empty. This file is a generator template; "
            "the notebooks in ./notebooks/ were generated by ad-hoc batch scripts."
        )
        return

    for t in TOPICS:
        write_nb(out_dir / t.filename, build(t))

    readme = [
        "# Python 基础教学 Notebooks\n\n",
        "目录：`notebooks/`\n\n",
        "打开方式：\n",
        "- `jupyter notebook` 或 `jupyter lab`\n\n",
        "说明：\n",
        "- 部分 Notebook 会在当前目录创建 `./_nb_artifacts/` 存放示例输出文件\n\n",
        "顺序：\n",
    ]
    for t in TOPICS:
        readme.append(f"- `{t.filename}`\n")
    (out_dir / "README.md").write_text("".join(readme), encoding="utf-8")

    for p in out_dir.glob("*.ipynb"):
        json.loads(p.read_text(encoding="utf-8"))

    print("generated", len(list(out_dir.glob("*.ipynb"))), "notebooks")


if __name__ == "__main__":
    generate()
